Fix mbed compile --flash
Unknown error is thrown while executing mbed compile --flash:

[mbed] ERROR: Unknown Error: local variable 'baudrate' referenced before assignment

Add the required argument to compile_ method.
This also fixes another error while mbed compile --flash --baudrate 9600:

[mbed] ERROR: Unknown Error: compile_() got an unexpected keyword argument 'baudrate'

This is a regression introduced by
https://github.com/ARMmbed/mbed-cli/pull/837