In the event your CWD has been removed this cleans up the error message while running mbed-cli.
Current error message:

Traceback (most recent call last):
  File "/usr/local/bin/mbed", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/mbed/mbed.py", line 2567, in main
    cwd_root = os.getcwd()
OSError: [Errno 2] No such file or directory

New error message:

[mbed] ERROR: Unable to get current directory: [Errno 2] No such file or directory
---